/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Negocio.Control.Persona;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author Andrés Mogollón
 */
public class InterfazFormulario extends javax.swing.JFrame {
    javax.swing.ImageIcon icono=new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Aprobado.png"));
    /**
     * Creates new form InterfazFormulario
     */
    public InterfazFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLTitulo = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLApellidos = new javax.swing.JLabel();
        JLCI = new javax.swing.JLabel();
        JLEmail = new javax.swing.JLabel();
        JLTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        JLImagenEmail = new javax.swing.JLabel();
        JLImagenNombre = new javax.swing.JLabel();
        JLImagenTelefono = new javax.swing.JLabel();
        JLImagenApellidos = new javax.swing.JLabel();
        JLImagenCI = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        JLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLTitulo.setText("Formulario de Datos");

        JLNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        JLNombre.setForeground(new java.awt.Color(255, 255, 255));
        JLNombre.setText("Nombre");
        JLNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JLNombreFocusLost(evt);
            }
        });
        JLNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JLNombreKeyTyped(evt);
            }
        });

        JLApellidos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        JLApellidos.setForeground(new java.awt.Color(255, 255, 255));
        JLApellidos.setText("Apellidos");

        JLCI.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        JLCI.setForeground(new java.awt.Color(255, 255, 255));
        JLCI.setText("CI");
        JLCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JLCIKeyTyped(evt);
            }
        });

        JLEmail.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        JLEmail.setForeground(new java.awt.Color(255, 255, 255));
        JLEmail.setText("Email");

        JLTelefono.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        JLTelefono.setForeground(new java.awt.Color(255, 255, 255));
        JLTelefono.setText("Teléfono");

        BotonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(128, 38, 126));
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonLimpiar.setForeground(new java.awt.Color(128, 38, 126));
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(128, 38, 126));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        JLImagenEmail.setMaximumSize(new java.awt.Dimension(30, 30));
        JLImagenEmail.setMinimumSize(new java.awt.Dimension(30, 30));
        JLImagenEmail.setPreferredSize(new java.awt.Dimension(30, 30));
        JLImagenEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JLImagenEmailFocusLost(evt);
            }
        });

        JLImagenNombre.setMaximumSize(new java.awt.Dimension(30, 30));
        JLImagenNombre.setMinimumSize(new java.awt.Dimension(30, 30));
        JLImagenNombre.setPreferredSize(new java.awt.Dimension(30, 30));

        JLImagenTelefono.setMaximumSize(new java.awt.Dimension(30, 30));
        JLImagenTelefono.setMinimumSize(new java.awt.Dimension(30, 30));
        JLImagenTelefono.setPreferredSize(new java.awt.Dimension(30, 30));
        JLImagenTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JLImagenTelefonoFocusLost(evt);
            }
        });

        JLImagenApellidos.setMaximumSize(new java.awt.Dimension(30, 30));
        JLImagenApellidos.setMinimumSize(new java.awt.Dimension(30, 30));
        JLImagenApellidos.setPreferredSize(new java.awt.Dimension(30, 30));
        JLImagenApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JLImagenApellidosFocusLost(evt);
            }
        });

        JLImagenCI.setMaximumSize(new java.awt.Dimension(30, 30));
        JLImagenCI.setMinimumSize(new java.awt.Dimension(30, 30));
        JLImagenCI.setPreferredSize(new java.awt.Dimension(30, 30));
        JLImagenCI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JLImagenCIFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(JLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JLTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLCI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtCI)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLImagenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLImagenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLImagenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLImagenApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLImagenCI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLCI)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLImagenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLImagenApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLImagenCI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(JLImagenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLImagenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonLimpiar)
                    .addComponent(BotonSalir))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        FondoFormulario AplicarFondo=new FondoFormulario();
        this.add(AplicarFondo , BorderLayout.SOUTH);
        AplicarFondo.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed

        dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        txtNombre.setText("");
        txtApellidos.setText("");
        txtCI.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        if(txtNombre.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Por favor ingrese el nombre");
        return;
        }
        if(txtApellidos.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Por favor ingrese el apellidos");
        return;
        }
        if(txtCI.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Por favor ingrese la cédula");
        return;
        }
        if(txtEmail.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Por favor ingrese el email");
        return;
        }
        if(txtTelefono.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Por favor ingrese el teléfono");
        return;
        }
        //Limpiaremos un poco el código haciendo variables nuevas
        String Nombre,Apellidos,CI,Email,Telefono;
        //Los llenaremos con las variables
        Nombre=txtNombre.getText();
        Apellidos=txtApellidos.getText();
        CI=txtCI.getText();
        Email=txtEmail.getText();
        Telefono=txtTelefono.getText();

        //y aquí nuestra respuesta de los datos bien agregados

        //JOptionPane.showMessageDialog(null,"Nombre: "+Nombre+" Apellidos: "+Apellidos+" CI: "+CI+" Email: "+Email+" Teléfono: "+Telefono);
        Persona persona=new Persona(Nombre,Apellidos,CI,Email,Telefono);
        //Agenda.GuardarPersona(persona);
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void JLNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLNombreKeyTyped
        if(txtNombre.getText().length()>=12){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_JLNombreKeyTyped

    private void JLCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLCIKeyTyped
        char TipoDeTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_JLCIKeyTyped

    private void JLNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JLNombreFocusLost
        if(txtNombre.getText().length()>=2){
            JLImagenNombre.setIcon(icono);
        }else{
            JLImagenNombre.setIcon(null);
        }
    }//GEN-LAST:event_JLNombreFocusLost

    private void JLImagenApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JLImagenApellidosFocusLost
        if(txtApellidos.getText().length()>=2){
            JLImagenApellidos.setIcon(icono);
        }else{
            JLImagenApellidos.setIcon(null);
        }
    }//GEN-LAST:event_JLImagenApellidosFocusLost

    private void JLImagenCIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JLImagenCIFocusLost
        if(txtCI.getText().length()>=2){
            JLImagenCI.setIcon(icono);
        }else{
            JLImagenCI.setIcon(null);
        }
    }//GEN-LAST:event_JLImagenCIFocusLost

    private void JLImagenEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JLImagenEmailFocusLost
        if(txtEmail.getText().length()>=2){
            JLImagenEmail.setIcon(icono);
        }else{
            JLImagenEmail.setIcon(null);
        }
    }//GEN-LAST:event_JLImagenEmailFocusLost

    private void JLImagenTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JLImagenTelefonoFocusLost
        if(txtTelefono.getText().length()>=2){
            JLImagenTelefono.setIcon(icono);
        }else{
            JLImagenTelefono.setIcon(null);
        }
    }//GEN-LAST:event_JLImagenTelefonoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel JLApellidos;
    private javax.swing.JLabel JLCI;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLImagenApellidos;
    private javax.swing.JLabel JLImagenCI;
    private javax.swing.JLabel JLImagenEmail;
    private javax.swing.JLabel JLImagenNombre;
    private javax.swing.JLabel JLImagenTelefono;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLTelefono;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
